# Generated by Django 6.0.4 on 2026-06-11 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDjango', '0003_opcionexamen_pregunta_alter_opcionexamen_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebDjango.curso')),
                ('ultimo_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progreso', to='WebDjango.videos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebDjango.user')),
            ],
            options={
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
