# Generated by Django 5.2.9 on 2026-01-28 20:51

import WebDjango.models
import WebDjango.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpcionExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("textoOpcion", models.CharField(max_length=600)),
                ("opcionCorrecta", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "WebDjango_opcionexamen",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tituloExamen", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=250, null=True)),
                ("descripcionModulo", models.CharField(max_length=550)),
                (
                    "imagenModulo",
                    models.ImageField(upload_to=WebDjango.models.rutasImagenes),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombrePais", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rol", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreCurso", models.CharField(max_length=45)),
                (
                    "moduloCurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WebDjango.modulo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="modulo",
            name="paisModulos",
            field=models.ManyToManyField(blank=True, to="WebDjango.pais"),
        ),
        migrations.CreateModel(
            name="PreguntaExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("textoPregunta", models.CharField(max_length=500)),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="WebDjango.examen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreUnidad", models.CharField(max_length=45)),
                (
                    "icono",
                    models.ImageField(
                        blank=True, null=True, upload_to="iconos_unidades/"
                    ),
                ),
                ("paises", models.ManyToManyField(to="WebDjango.pais")),
            ],
        ),
        migrations.AddField(
            model_name="modulo",
            name="unidadModulos",
            field=models.ManyToManyField(blank=True, to="WebDjango.unidad"),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreUser", models.CharField(max_length=45)),
                ("cargo", models.CharField(max_length=45)),
                (
                    "ROL_idrol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WebDjango.rol",
                    ),
                ),
                (
                    "Unidad_idUnidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WebDjango.unidad",
                    ),
                ),
                (
                    "paisUser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WebDjango.pais",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreVideo", models.CharField(max_length=100)),
                (
                    "video",
                    models.FileField(
                        upload_to=WebDjango.models.rutasVideos,
                        validators=[WebDjango.validators.duracion_video],
                    ),
                ),
                ("ordenVideos", models.PositiveIntegerField(default=0)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="WebDjango.curso",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="examen",
            name="video",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examen",
                to="WebDjango.videos",
            ),
        ),
        migrations.CreateModel(
            name="ResultadoCuestionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje", models.PositiveIntegerField()),
                ("aprobado", models.BooleanField(default=False)),
                ("intento", models.PositiveIntegerField(default=1)),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WebDjango.examen",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WebDjango.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "examen", "intento")},
            },
        ),
    ]
