# Generated by Django 6.0.4 on 2026-05-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebDjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionexamen',
            options={},
        ),
    ]
