# Generated by Django 6.0.4 on 2026-05-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDjango', '0002_alter_opcionexamen_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionexamen',
            name='pregunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='WebDjango.preguntaexamen'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='opcionexamen',
            table=None,
        ),
    ]
